package(default_visibility = ["//visibility:public"])

java_binary(
    name = "run_sample",
    srcs = ["Main.java"],
    main_class = "binary.Main",
    deps = ["//src/build:sample"],
)

java_binary(
    name = "run_infinite_loop",
    srcs = ["InfiniteLoop.java"],
    main_class = "binary.InfiniteLoop",
)
